sudo: false

language: erlang
otp_release:
    - 22.0
    - 21.3
env:
    - TEST_MODE=regular
    - TEST_MODE=docker

branches:
    only:
        - master

addons:
    apt:
        packages:
            - libexpat1-dev

install: make compile
script:
    - if [ 'regular' = $TEST_MODE ]; then make test; fi
    - if [ 'regular' = $TEST_MODE ]; then rebar3 dialyzer; fi
    - if [ 'regular' = $TEST_MODE ]; then rebar3 xref; fi
    - if [ 'docker' = $TEST_MODE ]; then OTP_VSN=${TRAVIS_OTP_RELEASE}-1 ./integration_test/build_docker_image.sh; fi
    - if [ 'docker' = $TEST_MODE ]; then ./integration_test/test_docker_image.sh; fi
    - if [ 'docker' = $TEST_MODE ]; then ./integration_test/test_distribute_scenario.sh; fi

cache:
    directories:
        - $HOME/.cache/rebar3
