sudo: false

language: erlang
otp_release:
    - 22.0
    - 21.3

branches:
    only:
        - master

addons:
    apt:
        packages:
            - libexpat1-dev

install: make compile
script:
    - make test
    - rebar3 dialyzer
    - rebar3 xref
    - OTP_VSN=${TRAVIS_OTP_RELEASE}-1 ./integration_test/build_docker_image.sh
    - ./integration_test/test_docker_image.sh
    - ./integration_test/test_distribute_scenario.sh

cache:
    directories:
        - $HOME/.cache/rebar3
