sudo: false

language: erlang
otp_release:
    - 19.3
    - 20.3
    - 21.2

branches:
    only:
        - master

addons:
    apt:
        packages:
            - libexpat1-dev

install: make compile
script:
    - make test
    - rebar3 dialyzer

cache:
    directories:
        - $HOME/.cache/rebar3
