sudo: false

language: erlang
otp_release:
    - 18.3
    - 19.3
    -  20.3
    - 21.2

branches:
    only:
        - master

addons:
    apt:
        packages:
            - libexpat1-dev

install: make compile
script:
    - make test
    - make dialyzer

cache:
    directories:
        - dialyzer
