os: linux
dist: xenial

language: erlang

otp_release:
    - 22.3
    - 21.3

env:
    - TEST_MODE=regular
    - TEST_MODE=integration

branches:
    only:
        - master

script:
    - if [ 'regular' = $TEST_MODE ]; then make test; fi
    - if [ 'integration' = $TEST_MODE ]; then make integration_test; fi

cache:
    directories:
        - $HOME/.cache/rebar3
