name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ${{ matrix.test-type }} test on OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['24.0', '23.3.1']
        test-type: ['regular', 'integration']
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: '3.16.1'
      - if: matrix.test-type == 'regular'
        run: make test
      - if: matrix.test-type == 'integration'
        run: make integration_test
        env:
          OTP_RELEASE: ${{ matrix.otp }}
